name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy-test:
    name: Deploy -> test
    runs-on: self-hosted
    steps:
      - name: baguesctl deploy test
        run: sudo /usr/local/bin/baguesctl app:deploy nueva_app_t1 --env test

  deploy-prod:
    name: Deploy -> prod
    runs-on: self-hosted
    needs: deploy-test
    environment: production
    steps:
      - name: baguesctl deploy prod
        run: sudo /usr/local/bin/baguesctl app:deploy nueva_app_t1 --env prod